+ MyMayaSuite 1.0 .
# Auto-generated by tools/generate_mod.py

# core
PYTHONPATH +:= core/scripts
MAYA_SCRIPT_PATH +:= core/scripts
XBMLANGPATH +:= core/resources/icons

# zxtMaya_M2Ue
PYTHONPATH +:= tools/zxtMaya_M2Ue/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_M2Ue/scripts
