+ MyMayaSuite 1.0 .
# Auto-generated by tools/generate_mod.py

# core
PYTHONPATH +:= core/scripts
MAYA_SCRIPT_PATH +:= core/scripts
XBMLANGPATH +:= core/resources/icons

# zxtMaya_M2Ue
PYTHONPATH +:= tools/zxtMaya_M2Ue/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_M2Ue/scripts

# zxtMaya_ConvertShader
PYTHONPATH +:= tools/zxtMaya_ConvertShader/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_ConvertShader/scripts
XBMLANGPATH +:= tools/zxtMaya_ConvertShader/resources/icons

# zxtMaya_AntiVirus
PYTHONPATH +:= tools/zxtMaya_AntiVirus/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_AntiVirus/scripts
XBMLANGPATH +:= tools/zxtMaya_AntiVirus/resources/icons

# zxtMaya_Alembic
PYTHONPATH +:= tools/zxtMaya_Alembic/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_Alembic/scripts
XBMLANGPATH +:= tools/zxtMaya_Alembic/resources/icons

# zxtMaya_Validate
PYTHONPATH +:= tools/zxtMaya_Validate/scripts
MAYA_SCRIPT_PATH +:= tools/zxtMaya_Validate/scripts
XBMLANGPATH +:= tools/zxtMaya_Validate/resources/icons
