+ MyMayaSuite 1.0 D:/GIT/zxtMaya_Suite
# Auto-generated by tools/generate_mod.py

# core
PYTHONPATH +:= D:/GIT/zxtMaya_Suite/core/scripts
MAYA_SCRIPT_PATH +:= D:/GIT/zxtMaya_Suite/core/scripts
XBMLANGPATH +:= D:/GIT/zxtMaya_Suite/core/resources/icons
