import argparse
import json
from pathlib import Path

HEADER = "# Auto-generated by tools/generate_mod.py\n"


def build_lines(manifest: dict) -> list[str]:
    root = manifest.get("root", "d:/git/zxtMaya_Suite")
    suite_name = manifest.get("suite_name", "MyMayaSuite")
    version = manifest.get("version", "1.0")

    lines: list[str] = [f"+ {suite_name} {version} {root}", HEADER.strip(), ""]
    for entry in manifest.get("entries", []):
        label = entry.get("name", "module")
        lines.append(f"# {label}")
        for section, key in (("PYTHONPATH", "python_paths"), ("MAYA_SCRIPT_PATH", "script_paths"), ("XBMLANGPATH", "icon_paths")):
            for relative in entry.get(key, []):
                lines.append(f"{section} +:= {relative}")
        lines.append("")
    return lines


def generate_mod(manifest_path: Path, target_path: Path) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    lines = build_lines(manifest)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Maya .mod file from suite manifest.")
    parser.add_argument("--maya", default="2024", help="Maya ????????????")
    parser.add_argument("--manifest", default="suite_manifest.json", help="????????")
    parser.add_argument("--output", help="??????? (.mod)")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        raise SystemExit(f"Manifest not found: {manifest_path}")

    if args.output:
        target_path = Path(args.output)
    else:
        target_path = Path("modules") / f"maya{args.maya}" / "MyMayaSuite.mod"

    generate_mod(manifest_path, target_path)
    print(f"Generated {target_path}")
